### ISSUE TITLE
Improve the error message in case of invalid locations

### ISSUE THREAD

**Issue by regnat** [tweag/porcupine#27]
If my yaml config for a pipeline (running with the http backend) contains something like 

```yaml
locations: 
  /Foo: http://foo:thisIsntAValidPortNumber/bar
```

then porcupine will fail with a message of the form

```
Location(s) "http://foo:thisIsntAValidPortNumber/bar" cannot be used by the location accessors in place.
```

While true, this isn't a really cool message to get because it doesn't tell me *why* the http backend couldn't recognize this url (and my first intuition as a user will be to think that the dev of the pipeline forgot to include the http backend).

I see two solutions to avoid this:

- Display the error messages from all the parsers
  
    This is probably the simplest (though not the nicest) solution. It would look something like

    ```
    Location(s) "http://foo:thisIsntAValidPortNumber/bar" cannot be used by the location accessors in place:
      backend "local" failed with: expected "/" but got "h"
      backend "http" failed with: expected digit but got "t"
      backend "s3" failed with: expected digit but got "t"
    ```

    (I just made up the actual error messages, these would probable be different and depend on the actual parser used by the backend)

- Have a way to register a certain backend depending on some part of the location (like the protocol field in an url or a specific field in a json object). For example every url with `http` as the protocol would be reserved by the `http` backend. In this case the final error message would look like

    ```
    Location(s) "http://foo:thisIsntAValidPortNumber/bar" look like an http location but the http parser failed with: expected digit but got "t"
    ```

    The advantage of this solution is that we would have a really different error message, like

    ```
    no registered location accessor for http urls
    ```

    Obviously this gives less flexibility to the location accessors, so we should evaluate whether the trade-off is worth it

**Comment by YPares** [comment]
@regnat Try and run with `--context-verb 3`

**Comment by YPares** [comment]
Concerning the `no registered location accessor for http urls` it's simpler: if all parser fail, we can try one last time to parse the location as a URL, and if that works, get its protocol and display that error.

**Comment by regnat** [comment]
Yep' but that would be terribly wrong given that in this case there is a location accessor supposed to parse http locations
