### ISSUE TITLE
Build failure: `showDocumentation` doctest out of date

### ISSUE THREAD

**Issue by curiousleo** [tweag/porcupine#59]
https://github.com/tweag/porcupine/commit/0b22731a9ea349158cad104d1728847dd138bc4a changed the signature of `showDocumentation` but did not update the doctest just above the function definition, thus introducing this build failure: https://circleci.com/gh/tweag/porcupine/496

This can be fixed by adding an additional parameter to the doctest invocation of `showDocumentation`.

**Comment by YPares** [comment]
Ah right thanks :) I updated that
